In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

 Loading dataset

In [4]:
df = pd.read_csv('C:\\Users\\Gurjeet\\Desktop\\ML\\diabetesdoc.csv')

In [5]:
df.shape

(390, 16)

In [6]:
df.head()

patient_number  cholesterol  glucose  hdl_chol chol_hdl_ratio  age  gender  \
0               1          193       77        49            3,9   19  female   
1               2          146       79        41            3,6   19  female   
2               3          217       75        54              4   20  female   
3               4          226       97        70            3,2   20  female   
4               5          164       91        67            2,4   20  female   

   height  weight   bmi  systolic_bp  diastolic_bp  waist  hip  \
0      61     119  22,5          118            70     32   38   
1      60     135  26,4          108            58     33   40   
2      67     187  29,3          110            72     40   45   
3      64     114  19,6          122            64     31   39   
4      70     141  20,2          122            86     32   39   

  waist_hip_ratio     diabetes  
0            0,84  No diabetes  
1            0,83  No diabetes  
2            0,89  No diabetes  
3            0,79  No diabetes  
4            0,82  No diabetes

In [7]:
df.isna().sum()

patient_number     0
cholesterol        0
glucose            0
hdl_chol           0
chol_hdl_ratio     0
age                0
gender             0
height             0
weight             0
bmi                0
systolic_bp        0
diastolic_bp       0
waist              0
hip                0
waist_hip_ratio    0
diabetes           0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   patient_number   390 non-null    int64 
 1   cholesterol      390 non-null    int64 
 2   glucose          390 non-null    int64 
 3   hdl_chol         390 non-null    int64 
 4   chol_hdl_ratio   390 non-null    object
 5   age              390 non-null    int64 
 6   gender           390 non-null    object
 7   height           390 non-null    int64 
 8   weight           390 non-null    int64 
 9   bmi              390 non-null    object
 10  systolic_bp      390 non-null    int64 
 11  diastolic_bp     390 non-null    int64 
 12  waist            390 non-null    int64 
 13  hip              390 non-null    int64 
 14  waist_hip_ratio  390 non-null    object
 15  diabetes         390 non-null    object
dtypes: int64(11), object(5)
memory usage: 48.9+ KB


In [14]:
df.describe()

cholesterol     glucose    hdl_chol         age      height  \
count   390.000000  390.000000  390.000000  390.000000  390.000000   
mean    207.230769  107.338462   50.266667   46.774359   65.951282   
std      44.666005   53.798188   17.279069   16.435911    3.918867   
min      78.000000   48.000000   12.000000   19.000000   52.000000   
25%     179.000000   81.000000   38.000000   34.000000   63.000000   
50%     203.000000   90.000000   46.000000   44.500000   66.000000   
75%     229.000000  107.750000   59.000000   60.000000   69.000000   
max     443.000000  385.000000  120.000000   92.000000   76.000000   

           weight  systolic_bp  diastolic_bp       waist         hip  
count  390.000000   390.000000    390.000000  390.000000  390.000000  
mean   177.407692   137.133333     83.289744   37.869231   42.992308  
std     40.407824    22.859528     13.498192    5.760947    5.664342  
min     99.000000    90.000000     48.000000   26.000000   30.000000  
25%    150.250000   122.000000     75.000000   33.000000   39.000000  
50%    173.000000   136.000000     82.000000   37.000000   42.000000  
75%    200.000000   148.000000     90.000000   41.000000   46.000000  
max    325.000000   250.000000    124.000000   56.000000   64.000000

droping patient_number column as it is not an  important feature

In [12]:
df.drop('patient_number', axis = 1 , inplace = True)

In [13]:
df.head()

cholesterol  glucose  hdl_chol chol_hdl_ratio  age  gender  height  weight  \
0          193       77        49            3,9   19  female      61     119   
1          146       79        41            3,6   19  female      60     135   
2          217       75        54              4   20  female      67     187   
3          226       97        70            3,2   20  female      64     114   
4          164       91        67            2,4   20  female      70     141   

    bmi  systolic_bp  diastolic_bp  waist  hip waist_hip_ratio     diabetes  
0  22,5          118            70     32   38            0,84  No diabetes  
1  26,4          108            58     33   40            0,83  No diabetes  
2  29,3          110            72     40   45            0,89  No diabetes  
3  19,6          122            64     31   39            0,79  No diabetes  
4  20,2          122            86     32   39            0,82  No diabetes

In [15]:
df = pd.get_dummies(df,drop_first= True)

In [16]:
df.head()

cholesterol  glucose  hdl_chol  age  height  weight  systolic_bp  \
0          193       77        49   19      61     119          118   
1          146       79        41   19      60     135          108   
2          217       75        54   20      67     187          110   
3          226       97        70   20      64     114          122   
4          164       91        67   20      70     141          122   

   diastolic_bp  waist  hip  ...  waist_hip_ratio_1,02  waist_hip_ratio_1,03  \
0            70     32   38  ...                     0                     0   
1            58     33   40  ...                     0                     0   
2            72     40   45  ...                     0                     0   
3            64     31   39  ...                     0                     0   
4            86     32   39  ...                     0                     0   

   waist_hip_ratio_1,04  waist_hip_ratio_1,05  waist_hip_ratio_1,06  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   waist_hip_ratio_1,07  waist_hip_ratio_1,08  waist_hip_ratio_1,09  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   waist_hip_ratio_1,14  diabetes_No diabetes  
0                     0                     1  
1                     0                     1  
2                     0                     1  
3                     0                     1  
4                     0                     1  

[5 rows x 310 columns]

In [22]:
##seperating X and Y
X = df.loc[:,['cholesterol','glucose','hdl_chol','age','height','weight','systolic_bp','diastolic_bp']].values
Y = df.loc[:,['diabetes_No diabetes']].values

In [23]:
X

array([[193,  77,  49, ..., 119, 118,  70],
       [146,  79,  41, ..., 135, 108,  58],
       [217,  75,  54, ..., 187, 110,  72],
       ...,
       [301,  90, 118, ..., 115, 218,  90],
       [232, 184, 114, ..., 127, 170,  82],
       [165,  94,  69, ..., 217, 160,  82]], dtype=int64)

In [24]:
#y

# Feature Scaling

feature scaling should be done when we are dealing with KNN algorithm

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [26]:
X

array([[-0.31901328, -0.5646553 , -0.07340058, ..., -1.44731175,
        -0.83807114, -0.98582201],
       [-1.37261932, -0.52743157, -0.5369832 , ..., -1.05084021,
        -1.27608741, -1.87597193],
       [ 0.21899831, -0.60187902,  0.21633855, ...,  0.23769232,
        -1.18848416, -0.83746369],
       ...,
       [ 2.10203888, -0.32270108,  3.92499948, ..., -1.54642964,
         3.54209161,  0.49776118],
       [ 0.55525555,  1.42681407,  3.69320817, ..., -1.24907598,
         1.43961349, -0.0956721 ],
       [-0.94669348, -0.24825362,  1.08555596, ...,  0.98107646,
         1.00159722, -0.0956721 ]])

In [29]:
##model was expecting 1d array as input
Y = Y.reshape(-1)

In [31]:
Y.shape

(390,)

In [32]:
##Splitting the data into train and test data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state = 0, test_size = 0.25)

In [33]:
##importing classification metrics
from sklearn.metrics import confusion_matrix,accuracy_score

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
acc_list = []
err_list = []
for i in range(1,25):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(X_train,Y_train)
    Y_pred = model.predict(X_test)
    acc = accuracy_score(Y_test,Y_pred)
    #print("For k = {}, accuracy = {}".format(i,acc
    acc_list.append(acc)
    err_list.append(1-acc)

In [37]:
plt.plot(list(range(1,25)),err_list,c = 'r')
plt.title('Error rate v/s K')
plt.xlabel('K')
plt.ylabel('Errror rate')
plt.show()

##### Note : from above graph we select 4 as K  value

# Model Building

In [40]:
model = KNeighborsClassifier(n_neighbors = 4)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

# Model Evaluation

In [41]:
confusion_matrix(Y_test,Y_pred)

array([[11,  9],
       [ 2, 76]], dtype=int64)

In [42]:
accuracy_score(Y_test,Y_pred)

0.8877551020408163